docs_dir: src
site_dir: build
site_name: amazing
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
    display_version: true
    collapse_navigation: false
    includehidden: true
    titles_only: true
markdown_extensions:
    - toc

html_theme_options : {
    'canonical_url': '',
    'analytics_id': '',
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'vcs_pageview_mode': '',
    # Toc options
    'collapse_navigation': False,
    'sticky_navigation': True,
    'navigation_depth': -1,
    'includehidden': True,
    'titles_only': True
}